### ISSUE TITLE
thebandfra.com - page not found

### ISSUE THREAD

**Issue by jusunkissed** [DeliciousTunes/thebandfra#1]
Du @dkastl ,
hab jetzt schon viel hier in Github geschnallt - aber bei the bandfra.com kommt page not found - was sehr seltsam ist, da unter pages eigentlich alles richtig ist. kannst du sehen, was ein fehler sein könnte?

![image](https://user-images.githubusercontent.com/6135434/116853251-0dfe3480-abf6-11eb-880b-41a362533ad9.png)

Interessant ist vielleicht, das die DOMAIN bei dd24 in einem komplettpaket mit Webhosting war. hab das aber davon abgelöst  und genau richtig angelegt.  Bei Mokoomba war es genauso und da hat es sofort geklappt. vielleicht ist es auch nur langsamer..... keine Ahnung. Mokoomba ging aber flott. darum bin ich iritiert.

**Comment by dkastl** [comment]
Hier geht es thebandfra.com
Dauert vielleicht ein Weilchen

**Comment by jusunkissed** [comment]
komisch - bei mir gehts weder am rechner noch am handy. versteh das nicht. aber mal abwarten. es kommt ne page not found. vielleicht ist bei dir noch die alte seite? es sollte der inhalt der webseite kommen und nicht nur ein bestätigung dass es verknüpft ist.

**Comment by jusunkissed** [comment]
@dkastl - irgendwas ist faul . geht noch immer nicht. bei luan auch nicht. der hat die seite noch nie davor geöffnet. verbingung geht, aber keine inhalte kommen

**Comment by jusunkissed** [comment]
ok war doch zeit - aber ganz schön lange diesesmal. verrückt. danke fürs hier dich antippen können.
